// Generated by CoffeeScript 1.7.1
(function() {
  var $, a, getWebGL, hasWebGL, init, isMobile, MOBILE_CONTROL_TYPE, s, u, _fn, _i, _len;

  $ = function(_) {
    return document.getElementById(_);
  };

  init = function(controlType, quality, hud, godmode) {
    var hexGL, progressbar;
    hexGL = new bkcore.hexgl.HexGL({
      document: document,
      width: window.innerWidth,
      height: window.innerHeight,
      container: $('main'),
      overlay: $('overlay'),
      gameover: $('step-5'),
      quality: quality,
      difficulty: 0,
      hud: hud === 1,
      controlType: controlType,
      godmode: godmode,
      track: 'Cityscape'
    });
    window.hexGL = hexGL;
    progressbar = $('progressbar');
    return hexGL.load({
      onLoad: function() {
        console.log('LOADED.');
        hexGL.init();
        $('step-3').style.display = 'none';
        $('step-4').style.display = 'block';
        // Re-zero the gyroscope to the user's current hold position the
        // moment gameplay actually starts.
        if (hexGL.components && hexGL.components.shipControls &&
            hexGL.components.shipControls.orientationController) {
          hexGL.components.shipControls.orientationController.recalibrate();
        }
        return hexGL.start();
      },
      onError: function(s) {
        return console.error("Error loading " + s + ".");
      },
      onProgress: function(p, t, n) {
        console.log("LOADED " + t + " : " + n + " ( " + p.loaded + " / " + p.total + " ).");
        return progressbar.style.width = "" + (p.loaded / p.total * 100) + "%";
      }
    });
  };

  u = bkcore.Utils.getURLParameter;

  isMobile = bkcore.Utils.isTouchDevice();

  // On mobile the cycler shows [TOUCH, GYROSCOPE]; this maps the cycler
  // index back to the canonical controlType ShipControls understands
  // (1 = TouchController, 4 = OrientationController).
  MOBILE_CONTROL_TYPE = [1, 4];

  s = [
    isMobile
      ? ['controlType', ['TOUCH', 'GYROSCOPE'], 0, 0, 'Controls: ']
      : ['controlType', ['KEYBOARD', 'TOUCH', 'LEAP MOTION CONTROLLER', 'GAMEPAD'], 0, 0, 'Controls: '],
    ['quality', ['LOW', 'MID', 'HIGH', 'VERY HIGH'], 3, 3, 'Quality: '],
    ['hud', ['OFF', 'ON'], 1, 1, 'HUD: '],
    ['godmode', ['OFF', 'ON'], 0, 1, 'Godmode: ']
  ];

  function canonicalControlType() {
    return isMobile ? MOBILE_CONTROL_TYPE[s[0][3]] : s[0][3];
  }

  _fn = function(a) {
    var e, f, _ref;
    a[3] = (_ref = u(a[0])) != null ? _ref : a[2];
    e = $("s-" + a[0]);
    (f = function() {
      return e.innerHTML = a[4] + a[1][a[3]];
    })();
    return e.onclick = function() {
      return f(a[3] = (a[3] + 1) % a[1].length);
    };
  };
  for (_i = 0, _len = s.length; _i < _len; _i++) {
    a = s[_i];
    _fn(a);
  }

  function proceedToLoad() {
    $('step-2').style.display = 'none';
    $('step-3').style.display = 'block';
    return init(canonicalControlType(), s[1][3], s[2][3], s[3][3]);
  }

  $('step-2').onclick = function() {
    var ct = canonicalControlType();
    if (isMobile && ct === 4 &&
        typeof DeviceOrientationEvent !== 'undefined' &&
        typeof DeviceOrientationEvent.requestPermission === 'function') {
      DeviceOrientationEvent.requestPermission()
        .then(function(state) {
          if (state !== 'granted') s[0][3] = 0; // fall back to TOUCH
          proceedToLoad();
        })
        .catch(function() {
          s[0][3] = 0;
          proceedToLoad();
        });
      return;
    }
    return proceedToLoad();
  };

  $('step-5').onclick = function() {
    return window.location.reload();
  };

  hasWebGL = function() {
    var canvas, gl;
    gl = null;
    canvas = document.createElement('canvas');
    try {
      gl = canvas.getContext("webgl");
    } catch (_error) {}
    if (gl == null) {
      try {
        gl = canvas.getContext("experimental-webgl");
      } catch (_error) {}
    }
    return gl != null;
  };

  function setupRotateOverlay() {
    if (!isMobile) return;
    var overlay = $('rotate-overlay');
    if (!overlay) {
      overlay = document.createElement('div');
      overlay.id = 'rotate-overlay';
      overlay.innerHTML = 'ROTATE YOUR PHONE<br>TO LANDSCAPE';
      document.body.appendChild(overlay);
    }
    function inPlayingPhase() {
      var ids = ['step-2', 'step-3', 'step-4'];
      for (var i = 0; i < ids.length; i++) {
        var el = $(ids[i]);
        if (el && el.style.display && el.style.display !== 'none') return true;
      }
      return false;
    }
    function update() {
      var portrait = window.innerHeight > window.innerWidth;
      var wasShown = overlay.style.display === 'flex';
      if (portrait && inPlayingPhase()) {
        overlay.style.display = 'flex';
      } else {
        overlay.style.display = 'none';
        // User just rotated into landscape — make this orientation the
        // gyro neutral so steering starts from zero.
        if (wasShown && window.hexGL && window.hexGL.components &&
            window.hexGL.components.shipControls &&
            window.hexGL.components.shipControls.orientationController) {
          window.hexGL.components.shipControls.orientationController.recalibrate();
        }
      }
    }
    window.addEventListener('resize', update);
    window.addEventListener('orientationchange', update);
    update();
  }

  function requestMobileFullscreen() {
    var el = document.documentElement;
    var req = el.requestFullscreen || el.webkitRequestFullscreen || el.mozRequestFullScreen || el.msRequestFullscreen;
    if (req) {
      try {
        var p = req.call(el);
        if (p && typeof p.catch === 'function') p.catch(function() {});
      } catch (e) {}
    }
    if (window.screen && screen.orientation && typeof screen.orientation.lock === 'function') {
      try { screen.orientation.lock('landscape').catch(function() {}); } catch (e) {}
    }
  }

  function paintStep2Help() {
    var step2 = $('step-2');
    var existing = $('gyro-help-msg');
    if (existing && existing.parentNode) existing.parentNode.removeChild(existing);
    var ct = canonicalControlType();
    if (ct === 4) {
      step2.style.backgroundImage = 'none';
      var msg = document.createElement('div');
      msg.id = 'gyro-help-msg';
      msg.className = 'gyro-help';
      msg.innerHTML = 'TILT YOUR PHONE TO STEER<br>HOLD TO ACCELERATE<br><br>TAP TO START';
      step2.appendChild(msg);
    } else {
      step2.style.backgroundImage = "url(css/help-" + ct + ".png)";
    }
  }

  if (!hasWebGL()) {
    getWebGL = $('start');
    getWebGL.innerHTML = 'WebGL is not supported!';
    getWebGL.onclick = function() {
      return window.location.href = 'http://get.webgl.org/';
    };
  } else {
    $('start').onclick = function() {
      if (isMobile) {
        requestMobileFullscreen();
        setupRotateOverlay();
      }
      $('step-1').style.display = 'none';
      $('step-2').style.display = 'block';
      return paintStep2Help();
    };
  }

}).call(this);
